# {{ now }}
FROM {{ baseImage }}

{% if systemPackages %}
RUN sudo apt-get update -q -y \
  && sudo apt-get install --no-install-recommends --fix-missing -y \
    {% for package in systemPackages %}
    {{ package }} \
    {% endfor %}
  && sudo apt-get autoremove -y \
  && sudo apt-get clean all
{% endif %}

ENV PYENV_ROOT /home/circleci/.pyenv

RUN git clone https://github.com/pyenv/pyenv.git $PYENV_ROOT \
  && git clone https://github.com/pyenv/pyenv-virtualenv.git $PYENV_ROOT/plugins/pyenv-virtualenv

ENV PATH $PYENV_ROOT/shims:$PYENV_ROOT/bin:$PATH

RUN PYTHON_CONFIGURE_OPTS="{{ pythonConfigureOptions|join(' ') }}" \
  CFLAGS="{{ cflags|join(' ')}}" \
  pyenv install {{ pythonVersion }} \
  && pyenv global {{ pythonVersion }} \
  && rm -f $PYENV_ROOT/cache/*

RUN pip install --no-cache-dir --upgrade setuptools pip
